sensor:
  - platform: template
    sensors:
      amanda_clock_location:
        friendly_name: "Amanda's Location"
        value_template: >-
          {% set sensor_id = "sensor.amanda_clock_location" %}
          {% set device_id = "device_tracker.iphone" %}

          {% set recently_speedy = state_attr(sensor_id, "speed_timestamp") != None and now().timestamp() - state_attr(sensor_id, "speed_timestamp") < (5 * 60) %}
          {% set device = states(device_id) %}
          {% set speed = 0 if state_attr(device_id, "speed") == None else state_attr(device_id, "speed") %}
          {% if device == "home" %}
            home
          {% elif device.startswith("work_") %}
            work
          {% elif device.startswith("store_") %}
            store
          {% elif device.startswith("family_") %}
            family
          {% elif speed >= 3 or recently_speedy %}
            travelling
          {% else %}
            lost
          {% endif %}
        attribute_templates:
          speed_timestamp: >-
            {% set sensor_id = "sensor.amanda_clock_location" %}
            {% set device_id = "device_tracker.iphone" %}

            {% set speed = 0 if state_attr(device_id, "speed") == None else state_attr(device_id, "speed") %}
            {% if speed >= 3 %}
              {{now().timestamp()}}
            {% else %}
              {{state_attr(sensor_id, "speed_timestamp")}}
            {% endif %}
      malcolm_clock_location:
        friendly_name: "Malcolm's Location"
        value_template: >-
          {% set sensor_id = "sensor.malcolm_clock_location" %}
          {% set device_id = "device_tracker.malcolm_s_phone" %}

          {% set recently_speedy = state_attr(sensor_id, "speed_timestamp") != None and now().timestamp() - state_attr(sensor_id, "speed_timestamp") < (5 * 60) %}
          {% set device = states(device_id) %}
          {% set speed = 0 if state_attr(device_id, "speed") == None else state_attr(device_id, "speed") %}
          {% if device == "home" %}
            home
          {% elif device.startswith("work_") %}
            work
          {% elif device.startswith("store_") %}
            store
          {% elif device.startswith("family_") %}
            family
          {% elif speed >= 3 or recently_speedy %}
            travelling
          {% else %}
            lost
          {% endif %}
        attribute_templates:
          speed_timestamp: >-
            {% set sensor_id = "sensor.malcolm_clock_location" %}
            {% set device_id = "device_tracker.malcolm_s_phone" %}

            {% set speed = 0 if state_attr(device_id, "speed") == None else state_attr(device_id, "speed") %}
            {% if speed >= 3 %}
              {{now().timestamp()}}
            {% else %}
              {{state_attr(sensor_id, "speed_timestamp")}}
            {% endif %}
rest_command:
  trigger_clock:
    url: http://192.168.0.120/moveHand
    method: POST
    headers:
      accept: "application/json, text/html"
    payload: '{"hand": "{{ hand }}","location": "{{ location }}"}'
    content_type:  'application/json; charset=utf-8'